[build]
builder = "dockerfile"
dockerfilePath = "../Dockerfile.backend"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
